[connections.postgresql]
dialect = "postgresql"
host = "persib-db.cluster-cm7jwitr9nnt.ap-southeast-1.rds.amazonaws.com"
port = "5432"
database = "preorder_production_eks"
username = "postgres"
password = "Qz9YWE8Spn5dK36fvCjrPVFa4XU7q2AyBDu"